### PR TITLE
Snd 274 happy flow

### PR DESCRIPTION
**Pull request by oleksiidn**
Happy flow MVP.

[UI part](https://www.figma.com/file/qVUaK5Z5FmgQV16C71RRCn/USCT-MVP?type=design&node-id=40-2194).

### CODE REVIEW

**Comment by oleksiidn** [comment]
Need to consider another [MVP](https://govstack-global.atlassian.net/wiki/spaces/DEMO/pages/188252172/Sandbox+MVP) vision.

**Comment by oleksiidn** [comment]
Let's consider [consent BB](https://github.com/GovStackWorkingGroup/bb-consent) in happy flow MVP.

**Comment by goforePM** [comment]
> Let's consider [consent BB](https://github.com/GovStackWorkingGroup/bb-consent) in happy flow MVP.

What do you mean consider consent BB involvement in happy flow?  If you mean this step, where the user checks the "awareness declaration" then Ok, but to involve the full scope of Concent BB functionality in NO

**Comment by oleksiidn** [comment]
https://github.com/GovStackWorkingGroup/sandbox/pull/2#issuecomment-1537966678


> > Let's consider [consent BB](https://github.com/GovStackWorkingGroup/bb-consent) in happy flow MVP.
> 
> What do you mean consider consent BB involvement in happy flow? If you mean this step, where the user checks the "awareness declaration" then Ok, but to involve the full scope of Concent BB functionality in NO

Yes, I meant  when  `user checks the "awareness declaration"`.
Thanks for reply.

**Pull request closed without merging**
